<?php

namespace App\Services;

final class EnvFileManager
{
    /** @param array<string, array<string, mixed>> $schema */
    public function __construct(private readonly array $schema)
    {
    }

    public function renderExample(): string
    {
        $output = [
            '# Generated by `php spark env:dump`. Do not edit by hand.',
            '# Copy this file to .env and replace every CHANGE-ME value.',
        ];
        $lastGroup = null;

        foreach ($this->schema as $name => $rules) {
            $group = $rules['group'] ?? 'Other';
            if ($group !== $lastGroup) {
                $output[] = '';
                $output[] = '# ' . $group;
                $lastGroup = $group;
            }

            $output[] = '# ' . $rules['description'];
            $output[] = '# Type: ' . $this->typeDescription($rules) . '; ' . $this->requirementDescription($rules);

            $value = $this->exampleValue($rules);
            $optionalWithoutValue = $value === '' && ! ($rules['required'] ?? false) && ! isset($rules['required_when']);
            $output[] = ($optionalWithoutValue ? '# ' : '') . $name . '=' . $value;
        }

        return implode("\n", $output) . "\n";
    }

    public function renderDocumentation(): string
    {
        $output = [
            '# Environment configuration',
            '',
            'This file is generated by `php spark env:docs` from `Config\\EnvSchema`.',
            'Run `php spark env:check` before starting the application and `php spark env:diff` after changing the schema.',
            '',
            '| Variable | Type | Required | Default | Description |',
            '| --- | --- | --- | --- | --- |',
        ];

        foreach ($this->schema as $name => $rules) {
            $default = array_key_exists('default', $rules) ? $this->displayValue($rules['default']) : '—';
            if (($rules['secret'] ?? false) === true && $default !== '—') {
                $default = '(secret)';
            }
            $output[] = sprintf(
                '| `%s` | %s | %s | %s | %s |',
                $name,
                $this->escapeTable($this->typeDescription($rules)),
                $this->escapeTable($this->requirementDescription($rules)),
                $this->escapeTable($default),
                $this->escapeTable((string) $rules['description']),
            );
        }

        $output[] = '';
        $output[] = 'Secret values must never use placeholders such as `CHANGE-ME`, `password`, or `your-secret-here`.';

        return implode("\n", $output) . "\n";
    }

    /** @return array{missing: list<string>, unexpected: list<string>, stale: bool} */
    public function diff(string $contents): array
    {
        preg_match_all('/^\s*#?\s*([A-Za-z][A-Za-z0-9_.]*)\s*=/m', $contents, $matches);
        $documented = array_values(array_unique($matches[1]));
        $declared = array_keys($this->schema);

        return [
            'missing' => array_values(array_diff($declared, $documented)),
            'unexpected' => array_values(array_diff($documented, $declared)),
            'stale' => $contents !== $this->renderExample(),
        ];
    }

    /** @param array<string, mixed> $rules */
    private function exampleValue(array $rules): string
    {
        if (($rules['secret'] ?? false) === true && (($rules['required'] ?? false) || isset($rules['required_when']))) {
            return 'CHANGE-ME';
        }
        if (array_key_exists('default', $rules)) {
            return $this->displayValue($rules['default']);
        }

        return (string) ($rules['example'] ?? '');
    }

    /** @param array<string, mixed> $rules */
    private function typeDescription(array $rules): string
    {
        if (($rules['type'] ?? null) === 'enum') {
            return 'enum (' . implode(', ', $rules['values']) . ')';
        }
        if (($rules['type'] ?? null) === 'int' && (isset($rules['min']) || isset($rules['max']))) {
            return sprintf('int (%s–%s)', $rules['min'] ?? '…', $rules['max'] ?? '…');
        }

        return (string) ($rules['type'] ?? 'string');
    }

    /** @param array<string, mixed> $rules */
    private function requirementDescription(array $rules): string
    {
        if (($rules['required'] ?? false) === true) {
            return 'required';
        }
        if (isset($rules['required_when'])) {
            $requirements = [];
            foreach ($rules['required_when'] as $name => $value) {
                $requirements[] = $name . '=' . $value;
            }

            return 'required when ' . implode(' and ', $requirements);
        }

        return 'optional';
    }

    private function displayValue(mixed $value): string
    {
        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        return (string) $value;
    }

    private function escapeTable(string $value): string
    {
        return str_replace('|', '\\|', $value);
    }
}
