apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: codeigniter-chat
data:
  mysql-database: "ci4_chat"
  mysql-user: "ci4user"
  redis-host: "redis"
  redis-port: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: codeigniter-chat
data:
  create.sql: |
    CREATE TABLE IF NOT EXISTS `ci_sessions` (
      `id` varchar(40) NOT NULL,
      `ip_address` varchar(45) NOT NULL,
      `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
      `data` blob NOT NULL,
      PRIMARY KEY (`id`),
      KEY `ci_sessions_timestamp` (`timestamp`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE IF NOT EXISTS `messages` (
      `id` int(7) NOT NULL AUTO_INCREMENT,
      `user` varchar(255) CHARACTER SET latin1 NOT NULL,
      `msg` text CHARACTER SET latin1 NOT NULL,
      `time` int(11) NOT NULL DEFAULT '0',
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;