apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - websocket-deployment.yaml
  - websocket-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - configmap.yaml
  - secrets.yaml
  - persistentvolume.yaml

commonLabels:
  app: codeigniter-chat
  version: v1.0.0